### ISSUE TITLE
Facebook leads page limitation

### ISSUE THREAD

**Issue by KiNGKiMO** [BADEP/addons#6]
The facebook leads graph link is limited to 25 leads per page, at the end of the page you'll find "Next" link....
or you can use the limit parameter like this:
https://graph.facebook.com/v2.12/form_id/leads?access_token=xxx&limit=9999 

Thanks.

**Comment by mmugnolo** [comment]
Hi i have a problem with an isntallation on Ubuntu 16 and Odoo Comunnity 11.

Can you help me. This is the message.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/odoo-11.0/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/odoo-11.0/addons/crm_facebook_leads/models/lead.py", line 90, in get_facebook_leads
    for lead in r['data']:
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo-11.0/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-11.0/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo-11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/odoo-11.0/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-11.0/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-11.0/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo-11.0/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-11.0/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-11.0/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo-11.0/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo-11.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo-11.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo-11.0/odoo/addons/base/ir/ir_cron.py", line 76, in method_direct_trigger
    self.sudo(user=cron.user_id.id).ir_actions_server_id.run()
  File "/home/odoo/odoo-11.0/odoo/addons/base/ir/ir_actions.py", line 554, in run
    res = func(action, eval_context=eval_context)
  File "/home/odoo/odoo-11.0/odoo/addons/base/ir/ir_actions.py", line 430, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/home/odoo/odoo-11.0/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/home/odoo/odoo-11.0/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/odoo/odoo-11.0/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/odoo-11.0/addons/crm_facebook_leads/models/lead.py", line 90, in get_facebook_leads
    for lead in r['data']:
ValueError: <class 'KeyError'>: "data" while evaluating
'model.get_facebook_leads()'

**Comment by UnixedIT** [comment]
After installation and connecting the Facebook page, it works successfully and get the forms successfully. but when run "model.get_facebook_leads()" manually form scheduled actions. it gives the same error. any help!

**Comment by KiNGKiMO** [comment]
UnixedIT, I had similar issue before, I updated the FB access token and it's fixed.
